site_name: 'Compose Material Dialogs'
site_description: 'A Material Dialog Builder for Jetpack Compose'
site_author: 'Pranav Maganti'
site_url: 'https://smwed.github.io/composepickers/'
remote_branch: gh-pages

docs_dir: docs

repo_name: 'composepickers'
repo_url: 'https://github.com/smwed/composepickers'

nav:
  - 'Overview': index.md
  - 'Core':
    - 'Guide': Core.md
    - 'API': api/core/index.html
  - 'Color':
    - 'Guide': ColorPicker.md
    - 'API': api/color/index.html
  - 'DateTime':
    - 'Guide': DateTimePicker.md
    - 'API': api/datetime/index.html

theme:
  name: material
  palette:
    - deep purple: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode